### ISSUE TITLE
Lack issue

### ISSUE THREAD

**Issue by iyhaoo** [BrainStOrmics/Spaco#2]
Hi,

Thanks for the nice package! There is an import issue in logging.py

AttributeError: module 'lack' has no attribute 'LoggerManager'

I search the LoggerManager and it seems from https://github.com/aristoteleo/spateo-release/blob/main/spateo/external/lack.py, however, it doesn't exist in your package...

**Comment by Jinerhal** [comment]
Thanks for noting this issue. I localized the lack dependency like in spateo, it should work now. Let me know if there is any other issues.

BTW, lack was supposed to refer to logging-release, which is still available on PyPI, (not the "lack" package on PyPI if you use pip install lack), but the github version of logging-release indeed seems terminated. So, thanks for the sugesttion.
