### ISSUE TITLE
ModuleNotFoundError: No module named 'spaco.external'

### ISSUE THREAD

**Issue by StopTheRain** [BrainStOrmics/Spaco#3]
![image](https://github.com/user-attachments/assets/be04a488-aeef-412d-927e-b58192add9df)
![image](https://github.com/user-attachments/assets/f2fc5801-7656-496b-8842-a7c544cca5af)
I have installed spaco in my environment and all dependencies are satisfied, but the runtime still shows ModuleNotFoundError: No module named 'spaco.external'

**Comment by colinwxl** [comment]
I have encountered the same issue.

**Comment by colinwxl** [comment]
@ZHANGDAPA , by downgrade the package to '0.2.0' using `pip install spaco-release==0.2.0`, obmits the error.

**Comment by Jinerhal** [comment]
@ZHANGDAPA @colinwxl Thanks for reporting this issue. It was a miss not adding spaco.external to setup.py when I was fixing the logging module related issue #2 . (so it was not recognized as a sub-package/module on the installation). Should be fixed now in 0.2.2!

**Comment by Jinerhal** [comment]
Let me know if it works, and I'll close this issue.

**Comment by StopTheRain** [comment]
> Let me know if it works, and I'll close this issue.

I have updated to the latest version and the error problem has been successfully solved. Thank you very much! !
